// 単語データをJavaScript変数として定義
const wordsDataCSV = `Word,POS,日本語訳,テキストで使われている文章 (例),その他語を使った英語の例文,単語を使った代表的な熟語など
issue,n,問題、論点,Climate change is a pressing issue for our generation.,The main issue is a lack of communication.,"environmental issues, social issues, raise an issue"
affect,v,影響を与える,Pollution can seriously affect human health.,His decision will directly affect your future.,"deeply affect, affect change, affect a person"
solve,v,解決する,Scientists are trying to solve the problem of food waste.,We need to work together to solve this mystery.,"solve a problem, solve a puzzle, solve a crime"
impact,n,影響、衝撃,The new technology had a significant impact on daily life.,The speech had a profound impact on the audience.,"positive impact, negative impact, have an impact on"
global,adj,世界的な、地球規模の,Global warming is a serious threat to our planet.,The internet has created a global community.,"global warming, global market, global economy"
develop,v,発展させる、開発する,Researchers are working to develop new energy sources.,She wants to develop her skills in coding.,"develop a skill, develop a plan, develop a new product"
reduce,v,減らす、削減する,We should try to reduce our use of plastic bags.,"To save money, we need to reduce our expenses.","reduce waste, reduce costs, reduce risk"
protect,v,保護する、守る,It is important to protect endangered species.,This law is designed to protect consumers.,"protect from, protect against, protect the environment"
resource,n,資源,Water is a vital resource for all living things.,Time is a valuable resource that we often waste.,"natural resources, human resources, allocate resources"
community,n,地域社会、共同体,Volunteering helps build a stronger community.,There is a strong sense of community in this village.,"local community, online community, community spirit"
provide,v,提供する、与える,This organization aims to provide support to local families.,The school will provide textbooks for all students.,"provide support, provide information, provide a service"
benefit,n,利益、恩恵,The new policy will bring many benefits to the public.,Learning a new language has many benefits.,"mutual benefit, for the benefit of, receive a benefit"
individual,n,個人,Each individual has the right to express their opinion.,The system allows for individual choice.,"individual rights, individual responsibility"
solution,n,解決策,Finding a practical solution to the traffic problem is urgent.,We are looking for a long-term solution.,"practical solution, temporary solution, find a solution"
effort,n,努力,Making a great effort is necessary for success.,His continuous effort paid off in the end.,"make an effort, joint effort, put in effort"
access,v,利用する、アクセスする,Students can access the library's online database.,Do you have access to the internet here?,"access information, gain access, restricted access"
support,v,支援する、支持する,Many people support the idea of renewable energy.,My parents always support my decisions.,"support a cause, support a family, provide support"
source,n,源、出所,The sun is the primary source of energy on Earth.,You should always check the source of information.,"reliable source, energy source, primary source"
various,adj,様々な、多様な,The museum displays various types of art from around the world.,There are various reasons why people choose to study abroad.,"various kinds of, various forms of, various factors"
require,v,必要とする、要求する,This task will require a lot of concentration.,The job description requires experience in coding.,"require effort, require attention, legally required"
system,n,制度、システム,The public transportation system in Japan is very efficient.,The human body has many complex systems.,"political system, education system, nervous system"
major,adj,主要な、大部分の,Poverty remains a major challenge in many developing countries.,Music is a major part of her life.,"major problem, major difference, major breakthrough"
establish,v,設立する、確立する,They plan to establish a new research center.,It's important to establish good study habits early on.,"establish a company, establish a relationship, establish rules"
promote,v,促進する、推進する,We need to promote healthy eating habits among children.,The campaign aims to promote peace and understanding.,"promote health, promote tourism, promote a product"
factor,n,要因、要素,Many factors contribute to climate change.,Cost is a key factor in our decision.,"contributing factor, risk factor, determining factor"
consequence,n,結果、成り行き,The drought had severe consequences for farmers.,Every action has its consequences.,"serious consequences, unforeseen consequences, suffer the consequences"
prevent,v,妨げる、防ぐ,Wearing a mask can help prevent the spread of disease.,We need to take steps to prevent further damage.,"prevent something from happening, prevent crime"
generate,v,生み出す、発生させる,Solar panels generate electricity from sunlight.,The new policy is expected to generate a lot of debate.,"generate electricity, generate income, generate interest"
approach,n,取り組み方、方法,We need a new approach to solve this complex problem.,His approach to learning is very practical.,"direct approach, indirect approach, take an approach"
significant,adj,重要な、意義深い,There has been a significant improvement in air quality.,This discovery is significant for the field of medicine.,"significant change, significant difference, significant impact"
attitude,n,態度、考え方,A positive attitude is crucial for success.,His attitude towards work has completely changed.,"positive attitude, negative attitude, change one's attitude"
contribute,v,貢献する、寄与する,Everyone should contribute to protecting the environment.,He decided to contribute his time to charity.,"contribute to, contribute money, contribute ideas"
efficient,adj,効率的な,The new machine is much more efficient than the old one.,We need to find a more efficient way to do this.,"efficient system, efficient method, energy-efficient"
challenge,n,課題、難題,Overcoming poverty is a huge challenge for many countries.,This project presents a new challenge for our team.,"face a challenge, overcome a challenge, rise to a challenge"
sustainable,adj,持続可能な,We need to find sustainable solutions for energy production.,Sustainable development is essential for the future.,"sustainable development, sustainable agriculture, sustainable lifestyle"
identify,v,特定する、見つける,We need to identify the root causes of the problem.,Can you identify the person who stole the bag?,"identify a problem, identify a need, identify oneself with"
research,n,研究、調査,Scientists are conducting research into new cancer treatments.,She is doing research for her master's thesis.,"scientific research, market research, conduct research"
ensure,v,確実にする、保証する,Please ensure that all doors are locked before you leave.,We need to ensure the safety of all employees.,"ensure safety, ensure success, ensure accuracy"
conserve,v,節約する、保護する,It's important to conserve water during a drought.,Efforts are being made to conserve wildlife habitats.,"conserve energy, conserve water, conserve nature"
potential,n,可能性、潜在能力,The student shows great potential in mathematics.,This technology has the potential to change the world.,"untapped potential, realize one's potential, have the potential to"
complex,adj,複雑な,The human brain is an incredibly complex organ.,This is a very complex issue with no easy answers.,"complex system, complex problem, complex relationship"
diverse,adj,多様な、多岐にわたる,Our city has a diverse population from many different cultures.,The company offers a diverse range of products.,"diverse cultures, diverse opinions, diverse perspectives"
urban,adj,都市の、都会の,Many young people are moving to urban areas for work.,Urban planning is crucial for future cities.,"urban area, urban development, urban life"
rural,adj,田舎の、地方の,Life in a rural area is often quieter than in the city.,He prefers the peace and quiet of rural living.,"rural area, rural community, rural landscape"
infrastructure,n,社会基盤、インフラ,The government is investing in improving the country's infrastructure.,Good infrastructure is essential for economic growth.,"public infrastructure, transport infrastructure"
strategy,n,戦略,The company developed a new marketing strategy.,What's your strategy for winning the game?,"long-term strategy, business strategy, winning strategy"
emphasize,v,強調する、力説する,The teacher emphasized the importance of teamwork.,I want to emphasize that safety is our top priority.,"emphasize the point, emphasize the need for"
aspect,n,側面、局面,We need to consider every aspect of the problem.,There are several important aspects to this proposal.,"key aspect, important aspect, different aspects"
outcome,n,結果、成果,The outcome of the experiment was unexpected.,What was the outcome of the meeting?,"positive outcome, negative outcome, desired outcome"
innovative,adj,革新的な,The company is known for its innovative designs.,We are seeking innovative solutions to current problems.,"innovative technology, innovative idea, innovative approach"
adapt,v,適応する,It takes time to adapt to a new culture.,We need to adapt our plans to the changing situation.,"adapt to, adapt oneself to, adapt something for"
crucial,adj,非常に重要な、決定的な,Communication is crucial for a successful team.,It's crucial that we act quickly.,"crucial role, crucial factor, crucial decision"
transform,v,変える、変形させる,Technology can transform the way we live and work.,The internet has transformed communication.,"transform into, transform a society"
undertake,v,引き受ける、着手する,The company decided to undertake a new research project.,She will undertake the responsibility of organizing the event.,"undertake a task, undertake a project, undertake research"
assess,v,評価する、査定する,We need to assess the risks before starting the project.,The teacher will assess the students' progress.,"assess the situation, assess the damage, assess performance"
integrate,v,統合する、一体化する,We need to integrate new ideas into our existing system.,The goal is to integrate all departments into one team.,"integrate into, integrate with, integrate information"
illustrate,v,説明する、例証する,The speaker used examples to illustrate his point.,This diagram will help to illustrate the process.,"illustrate a point, illustrate with examples"
numerous,adj,多数の、多くの,There are numerous benefits to living in the countryside.,He has traveled to numerous countries around the world.,"numerous examples, numerous studies, numerous reasons"
enhance,v,向上させる、高める,Exercise can enhance your physical and mental health.,We are working to enhance the quality of our services.,"enhance performance, enhance reputation, enhance beauty"
conclude,v,結論付ける、終える,The report concludes that the new policy is effective.,The meeting concluded with a vote.,"conclude that, conclude a discussion, conclude an agreement"
despite,prep,～にもかかわらず,"Despite the heavy rain, the game continued.",She succeeded despite facing many difficulties.,"despite the fact that, despite everything"
nevertheless,adv,それにもかかわらず,"It was raining heavily; nevertheless, we went for a walk.","The work was difficult; nevertheless, she finished it on time.",
whereas,conj,～である一方、～に対して,"Some people prefer coffee, whereas others prefer tea.","He is tall, whereas his brother is quite short.",
tendency,n,傾向,There is a growing tendency for young people to use social media.,She has a tendency to talk too much when she's nervous.,"have a tendency to, a strong tendency"
capacity,n,能力、収容能力,The hall has a seating capacity of 500 people.,He has a great capacity for learning new things.,"mental capacity, storage capacity, production capacity"
perspective,n,視点、見方,Try to look at the situation from a different perspective.,His unique perspective offered new insights.,"from a different perspective, gain perspective"
feature,n,特徴、特色,The main feature of this phone is its long battery life.,The new car has many advanced safety features.,"key feature, distinguishing feature, special feature"
indicate,v,示す、指し示す,The survey results indicate a shift in public opinion.,A red light indicates danger.,"indicate that, indicate a trend, indicate a change"
demonstrate,v,実証する、示す,The experiment will demonstrate the principles of physics.,She demonstrated how to use the new software.,"demonstrate skills, demonstrate knowledge, demonstrate a point"
distinguish,v,区別する、見分ける,It's difficult to distinguish between the twins.,Can you distinguish fact from fiction?,"distinguish between, distinguish from"
approximately,adv,およそ、約,The event attracted approximately 200 visitors.,The journey will take approximately three hours.,"approximately equal to, approximately 50%"
considerable,adj,かなりの、相当な,The project required a considerable amount of time and effort.,She has gained a considerable amount of experience.,"considerable amount, considerable difference, considerable success"
alternative,n,代替案、選択肢,We need to find an alternative energy source.,Is there an alternative route we can take?,"viable alternative, alternative solution, explore alternatives"
interpret,v,解釈する、説明する,It's important to correctly interpret the data.,How do you interpret this poem?,"interpret data, interpret a dream, interpret a text"
precise,adj,正確な、精密な,We need to get a precise measurement of the ingredients.,He gave us very precise instructions.,"precise details, precise moment, precise definition"
emphasize,v,強調する、力説する,The teacher emphasized the importance of teamwork.,I want to emphasize that safety is our top priority.,"emphasize the point, emphasize the need for"
sequence,n,連続、順序,The events occurred in a specific sequence.,It's important to follow the correct sequence of steps.,"in sequence, historical sequence, logical sequence"
predict,v,予測する、予言する,It's difficult to predict the future of technology.,Experts predict that prices will rise.,"predict the future, predict an outcome"
illustrate,v,説明する、例証する,The speaker used examples to illustrate his point.,This diagram will help to illustrate the process.,"illustrate a point, illustrate with examples"
criteria,n,基準、標準,What are the criteria for admission to the university?,We evaluate candidates based on several criteria.,"selection criteria, evaluation criteria, meet the criteria"
fundamental,adj,基本的な、根本的な,Education is a fundamental right for all children.,Understanding these fundamental principles is crucial.,"fundamental rights, fundamental principle, fundamental change"
concept,n,概念、考え,He struggled to grasp the basic concept of physics.,The concept of freedom is central to their philosophy.,"abstract concept, key concept, explain a concept"
initial,adj,最初の、当初の,The initial plan was to finish the project by June.,My initial reaction was surprise.,"initial stage, initial reaction, initial public offering"
subsequent,adj,その後の、次に続く,The subsequent events proved his theory correct.,Her illness and subsequent recovery were remarkable.,"subsequent events, subsequent research, subsequent analysis"
prior,adj,前の、以前の,You need to have prior experience for this job.,This decision was made prior to my arrival.,"prior to, prior knowledge, prior arrangement"
acquire,v,習得する、獲得する,Students can acquire new knowledge through reading.,She managed to acquire a rare stamp for her collection.,"acquire knowledge, acquire skills, acquire a language"
evaluate,v,評価する,We need to evaluate the effectiveness of the new program.,The manager will evaluate your performance.,"evaluate performance, evaluate a proposal, objectively evaluate"
component,n,構成要素、部品,A computer has many different components.,Trust is an essential component of any healthy relationship.,"key component, main component, structural component"
mechanism,n,仕組み、メカニズム,The human body has a complex immune mechanism.,The government is trying to put a mechanism in place to prevent corruption.,"defense mechanism, coping mechanism, regulatory mechanism"
clarify,v,明確にする、はっきりさせる,Could you please clarify what you mean by that?,"The instructions were confusing, so I asked him to clarify.","clarify a point, clarify the situation"
perceive,v,知覚する、認識する,We often perceive the world differently based on our experiences.,How do you perceive the current economic situation?,"perceive as, perceive danger, perceive reality"
distribute,v,分配する、配布する,The organization will distribute food to those in need.,Books were distributed to all the students.,"distribute goods, distribute wealth, distribute leaflets"
indicate,v,示す、指し示す,The survey results indicate a shift in public opinion.,A red light indicates danger.,"indicate that, indicate a trend, indicate a change"
sufficient,adj,十分な、足りる,We have sufficient evidence to prove his guilt.,Do you have sufficient time to complete the task?,"sufficient amount, sufficient evidence, sufficient funds"
ultimate,adj,究極の、最終的な,The ultimate goal is to achieve world peace.,Winning the championship is his ultimate ambition.,"ultimate goal, ultimate aim, ultimate responsibility"
undergo,v,経験する、受ける,The building will undergo major renovations next month.,He had to undergo surgery after the accident.,"undergo a change, undergo treatment, undergo a process"
widespread,adj,広範囲にわたる、普及している,There is widespread concern about the rise in crime.,The new fashion trend became widespread very quickly.,"widespread use, widespread support, widespread belief"
constantly,adv,絶えず、常に,Technology is constantly evolving.,She is constantly checking her phone.,"constantly changing, constantly improving"
consequently,adv,その結果、ゆえに,"He failed the exam; consequently, he had to retake the course.","She didn't study; consequently, she didn't pass the test.",
moreover,adv,その上、さらに,"The food was delicious; moreover, the service was excellent.","He is a talented musician; moreover, he is a great composer.",
nevertheless,adv,それにもかかわらず,"It was raining heavily; nevertheless, we went for a walk.","The work was difficult; nevertheless, she finished it on time.",
whereas,conj,～である一方、～に対して,"Some people prefer coffee, whereas others prefer tea.","He is tall, whereas his brother is quite short.",
substance,n,物質、実体,Water is an essential substance for life.,The police found a suspicious substance in his bag.,"chemical substance, harmful substance, control substance"
distinct,adj,明らかな、はっきり区別できる,There are three distinct phases in the project.,The two cultures have distinct characteristics.,"distinct advantage, distinct possibility, distinct from"
emerge,v,現れる、浮上する,New problems began to emerge after the system update.,The truth finally emerged after a long investigation.,"emerge from, emerge victorious, new challenges emerge"
facilitate,v,容易にする、促進する,Technology can facilitate communication between people.,Good planning will facilitate the smooth running of the event.,"facilitate learning, facilitate growth, facilitate communication"
implement,v,実行する、実施する,The government decided to implement a new policy.,We need to implement these changes immediately.,"implement a plan, implement a strategy, implement a decision"
integral,adj,不可欠な、統合された,Trust is an integral part of any strong relationship.,These traditions are an integral part of their culture.,"integral part, integral role"
interact,v,交流する、相互に作用する,Students have opportunities to interact with native speakers.,How do different cultures interact with each other?,"interact with, interact socially"
maximize,v,最大限にする、最大限に活用する,We need to maximize our profits while minimizing costs.,The goal is to maximize efficiency.,"maximize potential, maximize benefits, maximize opportunities"
minimize,v,最小限にする、最小限に抑える,We need to minimize the risk of failure.,Try to minimize the amount of waste you produce.,"minimize risk, minimize damage, minimize costs"
overcome,v,克服する,She worked hard to overcome her shyness.,We must overcome these challenges together.,"overcome difficulties, overcome fear, overcome obstacles"
phenomenon,n,現象,Global warming is a complex natural phenomenon.,The aurora borealis is a beautiful natural phenomenon.,"natural phenomenon, social phenomenon, common phenomenon"
prioritize,v,優先する,You need to prioritize your tasks based on importance.,We must prioritize environmental protection.,"prioritize tasks, prioritize safety, prioritize spending"
pursue,v,追求する、追い求める,He decided to pursue a career in medicine.,She is determined to pursue her dreams.,"pursue a career, pursue an education, pursue happiness"
reliable,adj,信頼できる、確かな,We need a reliable source of information.,This car is very reliable and rarely breaks down.,"reliable source, reliable information, reliable friend"
sequence,n,連続、順序,The events occurred in a specific sequence.,It's important to follow the correct sequence of steps.,"in sequence, historical sequence, logical sequence"
sufficient,adj,十分な、足りる,We have sufficient evidence to prove his guilt.,Do you have sufficient time to complete the task?,"sufficient amount, sufficient evidence, sufficient funds"
ultimate,adj,究極の、最終的な,The ultimate goal is to achieve world peace.,Winning the championship is his ultimate ambition.,"ultimate goal, ultimate aim, ultimate responsibility"
undergo,v,経験する、受ける,The building will undergo major renovations next month.,He had to undergo surgery after the accident.,"undergo a change, undergo treatment, undergo a process"
unique,adj,独自の、唯一の,Each person has their own unique fingerprint.,The design of this building is truly unique.,"truly unique, unique opportunity, unique characteristic"
valid,adj,正当な、妥当な,You make a valid point.,Is your passport still valid?,"valid argument, valid reason, valid point"
vulnerable,adj,脆弱な、弱い立場にある,Children are often more vulnerable to illness.,The old bridge is vulnerable to strong winds.,"vulnerable to attack, vulnerable group, feel vulnerable"
whereas,conj,～である一方、～に対して,"Some people prefer coffee, whereas others prefer tea.","He is tall, whereas his brother is quite short.",
adequate,adj,十分な、適切な,Do you have adequate funds for the trip?,The punishment was not adequate for the crime.,"adequate amount, adequate supply, adequate preparation"
advocate,v/n,提唱する、主張する/提唱者,Many organizations advocate for human rights.,She is a strong advocate for environmental protection.,"advocate for, advocate against, a strong advocate"
allocate,v,割り当てる、配分する,The government decided to allocate more funds to education.,We need to allocate our resources carefully.,"allocate funds, allocate time, allocate resources"
alter,v,変える、変更する,He had to alter his plans due to the bad weather.,You can alter the size of the image.,"alter a plan, alter course, alter behavior"
anticipate,v,予期する、予測する,We anticipate a large crowd at the concert.,She didn't anticipate any problems.,"anticipate problems, anticipate needs, anticipate success"
apparent,adj,明らかな、明白な,It was apparent that he was not happy.,The reason for his absence was not apparent.,"it is apparent that, make apparent"
bias,n,偏見、先入観,The report showed a clear bias towards one political party.,We need to avoid bias in our research.,"racial bias, unconscious bias, overcome bias"
compensate,v,補償する、埋め合わせる,The company had to compensate him for the damage.,Nothing can compensate for the loss of a loved one.,"compensate for, compensate someone for something"
comprise,v,構成する、～から成る,The team comprises five members.,The book comprises ten chapters.,"comprise of (less common), be comprised of"
confront,v,直面する、立ち向かう,We must confront the challenges ahead.,He had to confront his fears.,"confront a problem, confront an issue"
consequence,n,結果、成り行き,The drought had severe consequences for farmers.,Every action has its consequences.,"serious consequences, unforeseen consequences, suffer the consequences"
constitute,v,構成する、～となる,These ingredients constitute a healthy meal.,His actions constitute a breach of contract.,"constitute a crime, constitute a threat"
consult,v,相談する、参照する,You should consult a doctor if you feel unwell.,Please consult the manual for more information.,"consult with, consult a specialist, consult a dictionary"
contemporary,adj,現代の、同時代の,Contemporary art is often challenging to understand.,She studies contemporary Japanese literature.,"contemporary art, contemporary issues, contemporary society"
contradict,v,矛盾する、否定する,His statements often contradict each other.,The evidence seems to contradict her story.,"contradict oneself, contradict a statement"
correspond,v,一致する、文通する,The figures do not correspond with our records.,She has been corresponding with a pen pal for years.,"correspond to, correspond with, in correspondence"
crucial,adj,非常に重要な、決定的な,Communication is crucial for a successful team.,It's crucial that we act quickly.,"crucial role, crucial factor, crucial decision"
deduce,v,推論する、演繹する,"From the evidence, we can deduce that he was innocent.",What can you deduce from these results?,"deduce from, deduce that"
depict,v,描写する、描く,The painting depicts a scene from ancient mythology.,The novel accurately depicts life in the 1950s.,"depict a scene, depict a character, depict a situation"
detrimental,adj,有害な、不利な,Smoking is detrimental to your health.,The policy could have a detrimental effect on the economy.,"detrimental effect, detrimental impact"
dispute,n/v,紛争、論争/異論を唱える,The two countries are in a border dispute.,They dispute the accuracy of the report.,"labor dispute, heated dispute, dispute a claim"
distort,v,歪める、ねじ曲げる,The media often distorts the truth.,Her account of the event was completely distorted.,"distort the truth, distort reality, distort facts"
elaborate,v,詳しく述べる、精巧に作る,Could you please elaborate on your earlier point?,He created an elaborate plan for the heist.,"elaborate on, elaborate design"
eliminate,v,除去する、排除する,We need to eliminate all possible errors.,The goal is to eliminate poverty worldwide.,"eliminate a threat, eliminate waste, eliminate competition"
enhance,v,向上させる、高める,Exercise can enhance your physical and mental health.,We are working to enhance the quality of our services.,"enhance performance, enhance reputation, enhance beauty"
equate,v,同一視する、等しいと見なす,You cannot equate wealth with happiness.,Many people equate success with financial gain.,"equate A with B, equate to"
erode,v,浸食する、蝕む,Wind and rain can erode the rocks over time.,His trust in her began to erode.,"erode confidence, erode soil, erode support"
exaggerate,v,誇張する、大げさに言う,He tends to exaggerate things when telling a story.,Don't exaggerate the difficulties; it's not that bad.,"exaggerate the truth, wildly exaggerate"
exclude,v,除外する、排除する,The price excludes breakfast.,Children under five are excluded from this activity.,"exclude from, exclude the possibility"
explicit,adj,明確な、明白な,The instructions were very explicit.,He gave me explicit directions to his house.,"explicit instructions, explicit consent, explicit message"
exploit,v,搾取する、利用する,Some companies exploit their workers by paying low wages.,We need to exploit new market opportunities.,"exploit resources, exploit a loophole, exploit a situation"
fluctuate,v,変動する、上下する,Stock prices can fluctuate greatly throughout the day.,The temperature will fluctuate between 10 and 15 degrees.,"prices fluctuate, moods fluctuate"
foster,v,育む、促進する,We need to foster a sense of community.,The program aims to foster creativity in children.,"foster growth, foster development, foster understanding"
fragile,adj,壊れやすい、もろい,The ancient pottery is very fragile.,The ecosystem of the coral reef is extremely fragile.,"fragile ecosystem, fragile economy, fragile peace"
halt,v/n,停止する/停止,The train came to a sudden halt.,The government decided to halt the construction project.,"come to a halt, bring to a halt, production halt"
hypothesis,n,仮説,Scientists formulated a hypothesis to explain the phenomenon.,We need to test this hypothesis through experimentation.,"form a hypothesis, test a hypothesis, prove/disprove a hypothesis"
implement,v,実行する、実施する,The government decided to implement a new policy.,We need to implement these changes immediately.,"implement a plan, implement a strategy, implement a decision"
imply,v,ほのめかす、暗示する,His silence seemed to imply agreement.,What are you trying to imply?,"imply that, imply a connection"
impose,v,課す、押し付ける,The government decided to impose a new tax.,Don't impose your views on others.,"impose a fine, impose a burden, impose rules"
incentive,n,誘因、奨励金,The company offers an incentive for employees to work overtime.,What's your incentive for taking on this difficult task?,"financial incentive, provide an incentive, economic incentive"
inherent,adj,固有の、生来の,There are inherent risks in mountain climbing.,The desire for knowledge is inherent in human nature.,"inherent risk, inherent quality, inherent flaw"
initiate,v,開始する、着手する,The committee decided to initiate a new project.,She took the initiative to initiate the conversation.,"initiate a project, initiate a discussion, initiate change"
integral,adj,不可欠な、統合された,Trust is an integral part of any strong relationship.,These traditions are an integral part of their culture.,"integral part, integral role"
interact,v,交流する、相互に作用する,Students have opportunities to interact with native speakers.,How do different cultures interact with each other?,"interact with, interact socially"
interpret,v,解釈する、説明する,It's important to correctly interpret the data.,How do you interpret this poem?,"interpret data, interpret a dream, interpret a text"
intervene,v,介入する、干渉する,The police had to intervene to break up the fight.,The government decided not to intervene in the dispute.,"intervene in, military intervention"
legitimate,adj,合法的な、正当な,His claim seemed perfectly legitimate.,Do you have a legitimate reason for being absent?,"legitimate reason, legitimate right, legitimate concern"
manipulate,v,操る、巧みに扱う,He tried to manipulate her feelings.,The software allows you to manipulate images.,"manipulate data, manipulate public opinion, manipulate a situation"
mediate,v,仲介する、調停する,The UN often mediates peace talks between warring nations.,He was asked to mediate the dispute between the two parties.,"mediate a dispute, mediate negotiations"
merely,adv,単に、ただの,He was merely joking; he didn't mean it seriously.,"It's merely a suggestion, not a command.","merely a coincidence, merely descriptive"
notably,adv,特に、著しく,The climate has changed notably in recent years.,"He is a talented artist, notably for his portraits.","notably absent, notably successful"
notion,n,概念、考え,He has a strange notion of what success means.,The notion of a perfect society is unrealistic.,"common notion, preconceived notion, popular notion"
omit,v,省略する、除外する,Please don't omit any important details.,He accidentally omitted a word from the sentence.,"omit a word, omit a detail, omit from"
optimum,adj,最適な、最善の,We need to find the optimum temperature for the reaction.,The optimum conditions for growth are still being studied.,"optimum solution, optimum performance, optimum level"
overt,adj,明白な、公然の,His anger was overt and clearly visible.,There was no overt sign of conflict.,"overt act, overt discrimination, overt hostility"
paradox,n,逆説、矛盾,It's a strange paradox that spending less can sometimes save more.,The film explores the paradox of human nature.,"a curious paradox, a striking paradox"
perceive,v,知覚する、認識する,We often perceive the world differently based on our experiences.,How do you perceive the current economic situation?,"perceive as, perceive danger, perceive reality"
persist,v,固執する、持続する,"If the pain persists, you should see a doctor.",She decided to persist with her efforts despite the difficulties.,"persist in, persist with, symptoms persist"
prerequisite,n,必要条件、前提条件,A high school diploma is a prerequisite for college admission.,What are the prerequisites for this course?,"a prerequisite for, meet the prerequisites"
presume,v,推定する、～だと思い込む,I presume you're hungry after your long journey.,Don't presume anything; ask directly.,"presume that, presume to be, presume guilt"
prevail,v,普及する、優勢である,Justice will eventually prevail.,Old customs still prevail in many rural areas.,"prevail over, prevail against, prevail in"
prioritize,v,優先する,You need to prioritize your tasks based on importance.,We must prioritize environmental protection.,"prioritize tasks, prioritize safety, prioritize spending"
profound,adj,深遠な、深い,The experience had a profound impact on his life.,She has a profound understanding of the subject.,"profound impact, profound knowledge, profound change"
prohibit,v,禁止する、妨げる,The law prohibits smoking in public buildings.,Parking is strictly prohibited here.,"prohibit from, prohibit the sale of"
prompt,v,促す、引き起こす,His question prompted a lively discussion.,What prompted you to change your mind?,"prompt action, prompt a response, prompted by"
proportion,n,割合、比率,A large proportion of the population lives in cities.,The proportion of women in management has increased.,"in proportion to, out of proportion, direct proportion"
protocol,n,規約、手順,The diplomat followed the strict protocol.,We need to follow the safety protocol.,"safety protocol, medical protocol, follow protocol"
radical,adj,根本的な、過激な,The new government proposed radical reforms.,He has some radical ideas about education.,"radical change, radical idea, radical reform"
random,adj,無作為の、でたらめの,The survey used a random sample of participants.,He picked a book at random from the shelf.,"at random, random selection, random sample"
reinforce,v,強化する、補強する,The positive feedback helped to reinforce her confidence.,We need to reinforce the roof of the building.,"reinforce an idea, reinforce a belief, reinforce a structure"
reluctant,adj,気が進まない、しぶしぶの,She was reluctant to accept the offer.,He felt reluctant to share his feelings.,"be reluctant to, reluctantly agree"
resolve,v,解決する、決心する,We need to resolve this conflict peacefully.,She resolved to study harder for the next exam.,"resolve a conflict, resolve an issue, resolve to do something"
retain,v,保持する、維持する,The company managed to retain most of its employees.,She struggled to retain all the information.,"retain control, retain possession, retain memories"
rigorous,adj,厳格な、綿密な,The scientific study involved rigorous testing.,The selection process is very rigorous.,"rigorous training, rigorous analysis, rigorous standards"
scenario,n,シナリオ、想定される事態,Let's consider a worst-case scenario.,The planner outlined various possible scenarios.,"worst-case scenario, likely scenario, hypothetical scenario"
scrutinize,v,綿密に調べる、吟味する,The lawyer scrutinized every detail of the contract.,His financial records were scrutinized by the auditors.,"scrutinize documents, scrutinize a proposal"
simulate,v,模擬する、シミュレーションする,The scientists used a computer to simulate the climate.,Pilots train in flight simulators.,"simulate conditions, simulate an environment"
solely,adv,もっぱら、単独で,He is solely responsible for the error.,The decision rests solely with the manager.,"solely responsible, solely dependent"
speculate,v,推測する、憶測する,We can only speculate about the reasons for his disappearance.,It's pointless to speculate about what might have been.,"speculate on, speculate about, media speculate"
stable,adj,安定した、堅固な,The economy is finally becoming stable.,The table is not very stable.,"stable economy, stable relationship, stable condition"
stimulate,v,刺激する、促進する,The government hopes to stimulate economic growth.,Reading can stimulate your imagination.,"stimulate growth, stimulate the economy, stimulate interest"
subsequent,adj,その後の、次に続く,The subsequent events proved his theory correct.,Her illness and subsequent recovery were remarkable.,"subsequent events, subsequent research, subsequent analysis"
substitute,n/v,代用品、代役/代わりにする,We can use honey as a substitute for sugar.,Can you substitute for me at the meeting?,"substitute for, substitute with, a good substitute"
suffice,v,十分である、足りる,A brief explanation will suffice.,This amount of food should suffice for everyone.,"suffice for, suffice it to say that"
supervise,v,監督する、指導する,A manager should supervise the work of their team.,She was hired to supervise the construction project.,"supervise staff, supervise children, closely supervise"
sustain,v,維持する、持続させる,The company managed to sustain its growth despite the recession.,It's difficult to sustain such a high level of effort.,"sustain growth, sustain life, sustain an argument"
synthesis,n,統合、総合,The report provides a synthesis of the research findings.,Protein synthesis is a vital process in cells.,"chemical synthesis, synthesis of ideas"
tangible,adj,有形の、明白な,We need to see tangible results from this investment.,There was no tangible evidence to support his claim.,"tangible benefits, tangible assets, tangible proof"
trait,n,特徴、特性,Honesty is an important trait to have.,He inherited many positive traits from his parents.,"personality trait, character trait, distinguishing trait"
transmit,v,伝える、送信する,Diseases can be transmitted through the air.,The radio station transmits programs around the world.,"transmit a signal, transmit information, transmit a disease"
underlying,adj,根本的な、潜在的な,What are the underlying causes of the problem?,There is an underlying tension in their relationship.,"underlying cause, underlying assumption, underlying issue"
utilize,v,利用する、活用する,We should utilize all available resources.,The company aims to utilize renewable energy sources.,"utilize resources, utilize technology, fully utilize"
validate,v,有効にする、正当性を証明する,The data helps to validate the theory.,His feelings were validated by her understanding.,"validate a claim, validate a study, validate a finding"
verify,v,確認する、検証する,You should verify the information before you publish it.,Please verify your identity by entering your password.,"verify the facts, verify a signature, verify authenticity"
viable,adj,実行可能な、存続可能な,The project is not financially viable.,We need to find a viable solution.,"viable option, viable alternative, financially viable"
volatile,adj,不安定な、揮発性の,The political situation in the region is very volatile.,Gasoline is a highly volatile liquid.,"volatile market, volatile situation, volatile prices"
warrant,v/n,正当化する、保証する/令状、根拠,His behavior does not warrant such harsh punishment.,The police obtained a search warrant.,"warrant attention, warrant an investigation, search warrant"`;

// CSVデータの検証機能
function validateWordsData() {
    try {
        const lines = wordsDataCSV.trim().split('\n');
        console.log(`CSVには ${lines.length - 1} 個の単語が含まれています`);
        
        // 各行のフィールド数をチェック
        const expectedFields = 6;
        let validRows = 0;
        for (let i = 1; i < lines.length; i++) {
            const fields = lines[i].split(',');
            if (fields.length >= expectedFields) {
                validRows++;
            }
        }
        console.log(`有効な単語データ: ${validRows} 個`);
        return validRows > 0;
    } catch (error) {
        console.error('CSVデータの検証中にエラーが発生:', error);
        return false;
    }
}

// アプリ起動時にデータを検証（開発用）
if (typeof window !== 'undefined') {
    window.addEventListener('load', function() {
        validateWordsData();
    });
}