// 単語データをJavaScript変数として定義
const wordsDataCSV = `Word,POS,日本語訳,テキストで使われている文章 (例),その他語を使った英語の例文,単語を使った代表的な熟語など
fashion,n,ファッション、流行,"The **fashion** industry has changed significantly in recent years.","She always stays up-to-date with the latest **fashion** trends.","fast fashion, fashion trend, high fashion, in fashion, out of fashion"
invest,v,投資する,"New companies have to **invest** millions of dollars in building factories and training employees.","Many people **invest** in real estate for long-term growth.","invest in, invest time/money, foreign investment"
brand,n,ブランド、銘柄,"When you shop for clothes, do you search for specific **brands**, or do you just buy what you like?","Luxury **brands** often use high-quality materials.","designer brand, brand loyalty, brand image"
economic,adj,経済の、経済学の,"The American Dream is changing due to various **economic** factors.","The country is facing an **economic** crisis.","economic growth, economic development, economic policy"
manage,v,管理する、なんとかする,"The company must **manage** its resources effectively.","I need to **manage** my time better.","manage money, manage a team, manage stress"
collection,n,（新製品の）コレクション,"Everyone was talking about the new designer **collections** at the spring fashion show in Milan.","The museum has an impressive **collection** of ancient artifacts.","fashion collection, new collection, private collection"
season,n,季節、シーズン,"My favorite store just launched their new coats for the fall **season**.","Ski resorts are busiest during the winter **season**.","fashion season, holiday season, peak season"
volume,n,量、容積,"When a clothing company raises its prices, it is not unusual for the company's sales **volume** to fall.","The new product generated a high **volume** of sales.","sales volume, trade volume, high volume"
cotton,n,綿,"**Cotton** clothes are cool and soft, but they wrinkle easily.","This shirt is made from 100% organic **cotton**.","cotton fabric, cotton gin, cotton plant"
retailer,n,小売業者,"A typical fast-fashion **retailer** can stock 10,000 designs annually.","Online **retailers** have revolutionized shopping.","online retailer, fashion retailer, major retailer"
significant,adj,重要な、意義深い,"The fashion industry has changed **significantly** in recent years.","There was a **significant** increase in traffic during rush hour.","significant impact, significant difference, statistically significant"
traditionally,adv,伝統的に,"**Traditionally**, fashion retailers created two clothing collections per year.","Holidays are **traditionally** a time for family gatherings.","traditionally known as, traditionally used for"
nowadays,adv,今日では、最近では,"**Nowadays**, in contrast, they can design and manufacture clothes in as little as four weeks.","**Nowadays**, many people work from home.",""
contrast,n,対比、対照,"Nowadays, in **contrast**, they can design and manufacture clothes in as little as four weeks.","The city lights are a beautiful **contrast** to the dark sky.","in contrast, by contrast, sharp contrast"
rapidly,adv,急速に、素早く,"The advantages of **rapidly** changing fashions are clear.","Technology is advancing **rapidly**.","rapidly increasing, rapidly changing, rapidly growing"
life cycle,n,ライフサイクル,"Shortening the **life cycle** of a product means that if a design doesn't sell well within a week, it is taken out of the stores.","Understanding the **life cycle** of a butterfly is fascinating.","product life cycle, complete life cycle"
concern,n,懸念、関心事,"Perhaps the biggest **concern** is the impact of wasted fast fashion on the environment.","Environmental protection is a growing **concern** for many people.","express concern, cause for concern, major concern"
impact,n,影響、衝撃,"Perhaps the biggest concern is the **impact** of wasted fast fashion on the environment.","The new policy will have a significant **impact** on the community.","positive impact, negative impact, have an impact on"
wasted,adj,無駄になった、無駄にされた,"Perhaps the biggest concern is the impact of **wasted** fast fashion on the environment.","It's a shame to see food being **wasted** when so many are hungry.","wasted effort, wasted opportunity, wasted time"
environment,n,環境,"Perhaps the biggest concern is the impact of wasted fast fashion on the **environment**.","We must work together to protect our planet's **environment**.","natural environment, protect the environment, damage the environment"
furthermore,adv,さらに、その上,"**Furthermore**, with fashions changing so quickly, cotton growers need to produce more cotton more cheaply and that means using more pesticides and chemicals.","He is a talented musician; **furthermore**, he is an excellent composer.",""
pesticides,n,殺虫剤、農薬,"Furthermore, with fashions changing so quickly, cotton growers need to produce more cotton more cheaply and that means using more **pesticides** and chemicals.","The use of **pesticides** can harm beneficial insects.","pesticide use, chemical pesticides"
chemicals,n,化学物質,"Furthermore, with fashions changing so quickly, cotton growers need to produce more cotton more cheaply and that means using more pesticides and **chemicals**.","Many household cleaning products contain harsh **chemicals**.","hazardous chemicals, industrial chemicals, chemical reaction"
theft,n,盗難、窃盗,"A third problem is the **theft** of ideas.","The company increased security measures to prevent **theft**.","identity theft, car theft, shoplifting"
attitude,n,態度、考え方,"People like you make me really angry. That is such a selfish **attitude**.","She has a positive **attitude** towards learning.","positive attitude, negative attitude, change one's attitude"
ethically,adv,倫理的に,"If the store has **ethically** produced clothes, then that is perfect.","The company strives to source its materials **ethically**.","ethically sourced, ethically sound, ethically produced"
advertising,n,広告、宣伝,"One of the biggest costs for retailers is **advertising**, but without it, customers have no way of getting information about stores and products.","The company launched a new **advertising** campaign.","online advertising, television advertising, advertising campaign"
consumers,n,消費者,"Smart **consumers** shop for clothes during the off-season.","Businesses need to understand the needs of their **consumers**.","consumer behavior, consumer rights, consumer goods"
designer labels,n,デザイナーブランド,"Some shoppers only buy clothes made by **designer labels**.","Many celebrities prefer to wear clothes from top **designer labels**.",""
competitors,n,競争相手、競合他社,"In the United States, Forever 21® and H&M® are **competitors**.","The company is constantly trying to innovate to stay ahead of its **competitors**.","key competitors, main competitors, direct competitors"
manufacturing,n,製造、生産,"In the clothing business, very little **manufacturing** is done in the United States.","The country's **manufacturing** sector has seen significant growth.","manufacturing industry, manufacturing process, manufacturing cost"
suppliers,n,供給業者,"China and India are the two biggest **suppliers** of cotton in the world.","We work closely with our **suppliers** to ensure quality.","raw material suppliers, trusted suppliers, sole supplier"
products,n,製品、商品,"As well as clothing companies, computer companies also find it cheaper to make their **products** overseas.","The company is launching several new **products** next month.","new products, consumer products, agricultural products"
overseas,adv/adj,海外へ、海外の,"Computer companies also find it cheaper to make their products **overseas**, mainly in Asia.","Many students choose to study **overseas**.","overseas market, overseas travel, work overseas"
conditions,n,状況、条件、環境,"The second problem with outsourcing is that working **conditions** in many offshore factories are uncomfortable and unsafe.","The severe weather **conditions** made travel difficult.","working conditions, living conditions, harsh conditions"
import,v,輸入する,"To give just one example, the United States alone **imported** more than 126 billion dollars' worth of textiles in 2015.","Countries often **import** goods that they cannot produce themselves.","import goods, import data, import duties"
multinational,adj,多国籍の,"Large **multinational** companies outsource their production to developing countries like Egypt or Cambodia.","Many large corporations today are **multinational**.","multinational corporation, multinational company"
offshore,adj,海外の、沖合の,"They use **offshore** production to do this.","The company decided to move its customer service operations **offshore**.","offshore production, offshore banking, offshore oil rig"
outsource,v,外部委託する,"Large multinational companies **outsource** their production to developing countries.","Many IT companies **outsource** their software development.","outsource to, outsource production, outsource services"
textile,n,織物、繊維,"The United States alone imported more than 126 billion dollars' worth of **textiles** in 2015.","The region is known for its traditional hand-woven **textiles**.","textile industry, textile production, textile design"
wage,n,賃金,"First, overseas workers usually receive very low **wages**.","The company announced an increase in the minimum **wage**.","minimum wage, hourly wage, fair wage"
consumption,n,消費,"The world's **consumption** of fashion is huge.","Energy **consumption** needs to be reduced.","energy consumption, domestic consumption, consumer consumption"
production,n,生産、製造,"Large multinational companies outsource their **production** to developing countries.","The factory increased its **production** to meet demand.","mass production, textile production, industrial production"
profits,n,利益、収益,"I believe they should contribute a much larger share of their massive **profits** to correcting these problems.","The company reported record **profits** this quarter.","make a profit, net profit, gross profit"
justify,v,正当化する,"These arguments may be correct, but in my opinion they do not **justify** the low wages and dangerous conditions found in many overseas factories today.","You need to **justify** your actions with clear reasons.","justify a decision, justify an expense, cannot justify"
stock,v,在庫を置く、仕入れる,"A typical fast-fashion retailer can **stock** 10,000 designs annually.","The store aims to **stock** a wide range of products.","stock up on, stock shelves, in stock, out of stock"
annually,adv,毎年、年に一度,"A typical fast-fashion retailer can stock 10,000 designs **annually**.","The company publishes its financial report **annually**.",""
advantages,n,利点、強み,"The **advantages** of rapidly changing fashions are clear.","There are many **advantages** to learning a foreign language.","competitive advantage, major advantage, take advantage of"
disadvantages,n,欠点、不利な点,"However, there are also a number of **disadvantages** to the fast-fashion approach.","One of the **disadvantages** of living in the city is the noise.","major disadvantage, have a disadvantage"
approach,n,方法、取り組み方,"However, there are also a number of disadvantages to the fast-fashion **approach**.","We need a new **approach** to solve this complex problem.","direct approach, indirect approach, take an approach"
enable,v,～を可能にする,"The low cost of clothes **enables** shoppers to buy several new sets of clothes each season instead of wearing the same amounts year after year.","Technology **enables** people to connect across long distances.","enable someone to do something, enable access to"
instead of,prep,～の代わりに,"This design enables shoppers to buy several new sets of clothes each season **instead of** wearing the same amounts year after year.","We decided to go to the park **instead of** the mall.","instead of doing something"
amounts,n,量、額,"This means that huge **amounts** of clothing are thrown away.","He donated large **amounts** of money to charity.","a large amount of, a small amount of, total amount"
grower,n,栽培者、生産者,"Cotton **growers** need to produce more cotton more cheaply.","Local **growers** supply fresh produce to the market.","fruit growers, organic growers"
high-end,adj,高級な、高価な,"At the other end of the fashion scale is **high-end** designer clothing.","The hotel offers **high-end** amenities.","high-end products, high-end market"
wealthy,adj,裕福な,"Fast fashion is becoming more and more popular, **wealthy** consumers worldwide are buying more and more expensive, luxury brands.","He comes from a very **wealthy** family.","wealthy businessman, wealthy nation"
luxury,adj,高級な、贅沢な,"**Luxury** brands often use high-quality materials.","They live in a **luxury** apartment.","luxury goods, luxury car, luxury lifestyle"
afford,v,～する余裕がある,"Many well-off customers buy designer clothes just to show that they can **afford** them.","I can't **afford** to buy a new car right now.","afford to do something, cannot afford"
quality,n,品質、質,"I prefer to pay for **quality**, and if the store has ethically produced clothes, then that is perfect.","The company is known for the high **quality** of its products.","high quality, poor quality, quality control"
lifespan,n,寿命、耐用年数,"Designer clothes have a longer **lifespan**.","The average **lifespan** of a smartphone is about two years.","product lifespan, human lifespan"
expensive,adj,高価な,"Expensive, luxury brands that will last longer.","That car is too **expensive** for me.","extremely expensive, surprisingly expensive"
environmentally friendly,phr adj,環境に優しい,"Longer lifespan, expensive designer clothes are more **environmentally friendly**.","The new car is more **environmentally friendly**.","environmentally friendly products, environmentally friendly practices"
claim,v/n,主張する、主張,"Supporters of outsourcing **claim** that it helps local economies.","He **claims** that he saw a UFO.","make a claim, false claim, truth claim"
harmful,adj,有害な,"Supporters of outsourcing claim that it helps local economies, but I believe it is **harmful** for two main reasons.","Smoking is **harmful** to your health.","harmful effects, harmful to, physically harmful"
receive,v,受け取る,"First, overseas workers usually **receive** very low wages.","I **received** a letter from my friend today.","receive an award, receive a message, receive feedback"
earn,v,稼ぐ、得る,"These workers often work 14 hours a day and **earn** less than a hundred dollars a month.","She works hard to **earn** a living.","earn money, earn a salary, earn a reputation"
unfair,adj,不公平な,"Such low wages are wrong and **unfair**.","It's **unfair** to blame him for everything.","unfair treatment, unfair advantage, unfair competition"
researcher,n,研究者,"As Priya Kapoor, a human rights **researcher** in Delhi, says, ""Garment workers in countries like India and Bangladesh can't afford to pay their basic needs like food and healthcare.""","University **researchers** are conducting a study on climate change.","lead researcher, medical researcher, academic researcher"
garment worker,phr n,縫製工、アパレル労働者,"**Garment workers** in countries like India and Bangladesh can't afford to pay their basic needs like food and healthcare.","The factory employs thousands of **garment workers**.",""
establish,v,確立する、設立する,"We need to **establish** a fair wage for the work they do.","The company aims to **establish** new branches overseas.","establish a company, establish a reputation, establish rules"
unsafe,adj,不安全な,"Working conditions in many offshore factories are uncomfortable and **unsafe**.","It is **unsafe** to swim in this river.","unsafe conditions, unsafe at any speed"
exposure,n,暴露、露出,"Workers are exposed to chemicals, dust, and unsafe levels of noise from sewing machines.","Prolonged **exposure** to the sun can be harmful.","exposure to, risk exposure, media exposure"
tragedy,n,悲劇,"A fire broke out at a garment factory in Dhaka, Bangladesh, that killed 1,127 people and injured 200. This was a terrible **tragedy**.","The accident was a terrible **tragedy** for the whole community.","human tragedy, personal tragedy, avert a tragedy"
injured,v,負傷した,"A fire broke out at a garment factory in Dhaka, Bangladesh, that killed 1,127 people and **injured** 200.","Several people were seriously **injured** in the car crash.","seriously injured, fatally injured"
expert,n,専門家,"I realize some **experts**, like the economist David Schneider, say that outsourcing benefits local economies.","Medical **experts** recommend regular exercise.","leading experts, field experts, ask the experts"
benefit,n,恩恵、利益,"Outsourcing **benefits** local economies by providing jobs at higher wages.","Learning a new language has many **benefits**.","mutual benefit, for the benefit of, receive a benefit"
agriculture,n,農業,"Supporters of outsourcing point out that people in developing countries often line up to take jobs in multinational factories, arguing that these jobs offer higher wages than local workers can make by working in **agriculture**.","The country's economy relies heavily on **agriculture**.","organic agriculture, modern agriculture"
argument,n,議論、主張,"These **arguments** may be correct, but in my opinion they do not justify the low wages and dangerous conditions found in many overseas factories today.","They had a heated **argument** about politics.","strong argument, logical argument, win an argument"
contribute,v,貢献する,"I believe they should **contribute** a much larger share of their massive profits to correcting these problems.","Everyone should **contribute** to protecting the environment.","contribute to, contribute money, contribute ideas"
massive,adj,巨大な、大規模な,"I believe they should contribute a much larger share of their **massive** profits to correcting these problems.","The project involved a **massive** amount of data.","massive success, massive change, massive effort"
located,adj,位置している,"They should contribute a much larger share of their massive profits to correcting these problems and improving social conditions in the countries where they are **located**.","The new library is conveniently **located** near the station.","located in, centrally located, conveniently located"
distinguishing,v,区別する,"**Distinguishing** fact from opinion is a key skill for academic readers.","It is often hard to **distinguish** between right and wrong.","distinguish between, distinguish from"
fact,n,事実,"A **fact** is a true statement that can be proven.","Please stick to the **facts** and avoid speculation.","proven fact, cold hard facts, in fact"
opinion,n,意見、見解,"An **opinion** usually expresses a person's idea, judgment or position.","Everyone is entitled to their own **opinion**.","hold an opinion, personal opinion, public opinion"
evidence,n,証拠,"What **evidence** does she use to support her claim?","The police found strong **evidence** linking him to the crime.","strong evidence, scientific evidence, lack of evidence"
alternative,n,代替案、選択肢,"Investing: Two **Alternatives** to Consider","We need to find an **alternative** solution to the problem.","alternative energy, alternative medicine"
financial,adj,財政的な、金融の,"What is the purpose of **financial** planning?","She works as a **financial** advisor.","financial crisis, financial success, financial aid"
property,n,不動産、財産,"For many people, buying **property** is the safest investment.","The university owns a lot of **property** in the city.","real property, intellectual property, private property"
mortgage,n,住宅ローン,"Most people don't have enough money to pay cash for a house, so they need to take out a **mortgage** from a bank.","They are struggling to pay their **mortgage** every month.","mortgage loan, mortgage payment, secure a mortgage"
borrow,v,借りる,"The money you **borrow** is called the principal and the amount you pay each year is called the interest rate.","Can I **borrow** your pen for a moment?","borrow money, borrow from, borrow a book"
principal,n,元金、元本,"The money you borrow is called the **principal** and the amount you pay each year is called the interest rate.","The **principal** amount of the loan was $100,000.","principal amount, principal and interest"
capital,n,資本、元手,"Once you pay back the **capital** and the interest, you own the property.","The company needs more **capital** to expand.","venture capital, working capital, human capital"
appreciate,v,価値が上がる、評価する,"Many people believe that real estate will always **appreciate** in value over time.","The house has **appreciated** significantly since they bought it.","appreciate in value, appreciate greatly"
liquid,adj,流動性の高い,"Real estate is not very **liquid**, so if you need to sell quickly, you may have to lower the price.","Gold is a highly **liquid** asset.","liquid assets, illiquid (antonym)"
fluctuate,v,変動する,"The stock market is very sensitive to the economy, and prices can **fluctuate** wildly.","Temperatures can **fluctuate** greatly throughout the day.","prices fluctuate, fluctuate wildly, fluctuate between"
volatility,n,変動性、不安定性,"Investing in stocks involves a high degree of **volatility**, which means that prices can rise and fall very quickly.","The **volatility** of the cryptocurrency market makes it risky.","market volatility, price volatility"
diversify,v,多角化する、分散する,"Another key strategy for investors is to **diversify** their portfolio.","It's important to **diversify** your income sources.","diversify investments, diversify a portfolio"
portfolio,n,ポートフォリオ,"Another key strategy for investors is to diversify their **portfolio**.","Her **portfolio** includes stocks, bonds, and real estate.","investment portfolio, diversified portfolio"
risk,n/v,リスク、危険,"Before making an investment, you should always do some research and decide how much **risk** you are willing to take.","Investing in the stock market involves a certain degree of **risk**.","take a risk, financial risk, high risk, low risk"
secure,adj,安全な、安定した,"For many people, buying property is the safest investment.","It's important to feel **secure** in your job.","feel secure, secure future, secure a loan"
assets,n,資産,"Once you pay back the capital and the interest, you own the property and it becomes an **asset**.","The company's total **assets** are valued at over $100 million.","financial assets, valuable assets, liquid assets"
achieve,v,達成する,"The American Dream is the belief that anyone can **achieve** success and happiness through hard work.","She worked hard to **achieve** her goals.","achieve a goal, achieve success, achieve a target"
generation,n,世代,"For many **generations**, Americans believed that if they worked hard, they could achieve their goals.","The younger **generation** is very concerned about climate change.","lost generation, future generation, next generation"
struggle,v,奮闘する、苦労する,"Many young people today cannot afford to buy a house and are **struggling** with large debts.","She is **struggling** to balance work and family life.","struggle with, struggle to do something, economic struggle"
debt,n,借金、負債,"Many young people today cannot afford to buy a house and are struggling with large **debts**.","He is trying to pay off his student **debt**.","pay off debt, accumulate debt, in debt"
crisis,n,危機,"They worry that the traditional American Dream is becoming impossible to achieve, especially after the 2008 financial **crisis**.","The company is facing a financial **crisis**.","economic crisis, financial crisis, political crisis"
trend,n,傾向、動向,"What are some of the recent **trends** that are making it harder to achieve the traditional American Dream?","The **trend** towards healthier eating is growing.","fashion trend, upward trend, downward trend"
wages,n,賃金,"The average worker's **wages** have not kept pace with the cost of living.","Many people are demanding higher **wages**.","minimum wage, hourly wage, low wages"
tuition,n,授業料,"In 1980, college **tuition** was about $3,000 per year, but today it is more than $10,000.","University **tuition** fees have increased significantly.","tuition fees, pay tuition"
healthcare,n,医療、ヘルスケア,"For many years, families could rely on their employers to provide **healthcare** benefits.","Access to affordable **healthcare** is a major concern.","public healthcare, private healthcare, healthcare system"
rely on,phr v,～に頼る、当てにする,"For many years, families could **rely on** their employers to provide healthcare benefits.","You can **rely on** me to get the job done.","rely on someone/something, rely heavily on"
benefits,n,給付、手当、恩恵,"For many years, families could rely on their employers to provide healthcare **benefits**.","The new policy offers various **benefits** to employees.","health benefits, employee benefits, fringe benefits"
retirement,n,引退、退職,"As a result, many people are now finding it difficult to save for **retirement**.","She is looking forward to her **retirement** next year.","retirement plan, retirement age, early retirement"
boom,n,好景気、急増,"Many economists predict an economic **boom** in the next few years.","The internet era led to a technology **boom**.","economic boom, housing boom, baby boom"
decline,n/v,減少、衰退,"There has been a steady **decline** in the number of people attending church.","The company has been in **decline** for several years.","economic decline, sharp decline, steady decline"
growth,n,成長、発展,"The country has experienced rapid economic **growth** in the last decade.","We are seeing strong **growth** in the tech sector.","economic growth, population growth, sustainable growth"
inflation,n,インフレーション、物価上昇,"**Inflation** causes the price of goods and services to rise over time.","High **inflation** can erode people's savings.","high inflation, low inflation, control inflation"
purpose,n,目的,"What is the **purpose** of financial planning?","The main **purpose** of the meeting is to discuss the budget.","for the purpose of, achieve a purpose, serve a purpose"
planning,n,計画、企画,"What is the purpose of financial **planning**?","Good **planning** is essential for any successful project.","financial planning, urban planning, strategic planning"
safer,adj,より安全な（safeの比較級）,"For many people, buying property is the **safer** investment.","Wearing a helmet makes cycling **safer**.",""
return,n,収益、リターン,"If you invest in stocks, you may lose money or you may make a good **return**.","The company's **return** on investment was higher than expected.","return on investment (ROI), high return, low return"
option,n,選択肢,"It's a difficult choice, but we have several **options**.","We need to consider all the available **options**.","best option, second option, have no option"
real estate,phr n,不動産,"Buying **real estate** can be a good long-term investment.","The **real estate** market is booming.","real estate agent, real estate development"
original,adj,元の、最初の,"The money you borrow is called the principal and the amount you pay back is the **original** amount plus an interest rate.","He returned the book to its **original** position.","original idea, original version, original plan"
lend,v,貸す,"If you **lend** money to a company, they will pay you back the original amount plus an interest rate.","Can you **lend** me some money until tomorrow?","lend money, lend a hand, lend an ear"
expected,adj,予想される、期待される,"The property can sometimes go down in value, especially if the economy slows down more than **expected**.","The outcome was not what we **expected**.","as expected, beyond expected, lower than expected"
long-term,adj,長期的な,"Real estate is generally considered a **long-term** investment.","We need a **long-term** solution to the problem.","long-term effects, long-term plan, long-term goal"
sensitive,adj,敏感な、影響を受けやすい,"The stock market is very **sensitive** to the economy.","He is very **sensitive** to criticism.","sensitive to, highly sensitive, politically sensitive"
wildly,adv,激しく、非常に,"The stock market is very sensitive to the economy, and prices can fluctuate **wildly**.","Her emotions fluctuated **wildly**.","fluctuate wildly, run wildly"
degree,n,程度、度合い,"Investing in stocks involves a high **degree** of volatility.","He showed a high **degree** of professionalism.","to a certain degree, high degree, low degree"
strategy,n,戦略,"Another key **strategy** for investors is to diversify their portfolio.","The company developed a new marketing **strategy**.","business strategy, marketing strategy, long-term strategy"
spread,v,広げる、分散する,"It is important to **spread** your money across different types of investments.","The news **spread** quickly throughout the town.","spread out, spread awareness, spread like wildfire"
diversified,adj,多角化された、分散された,"A **diversified** portfolio can help reduce risk.","She has a **diversified** range of interests.","diversified portfolio, diversified economy"
belief,n,信念、確信,"The American Dream is the **belief** that anyone can achieve success and happiness through hard work.","He has a strong **belief** in justice.","strong belief, common belief, personal belief"
opportunity,n,機会,"It is the **opportunity** to get a good job and a college education.","This is a great **opportunity** to learn something new.","seize an opportunity, miss an opportunity, equal opportunity"
house ownership,phr n,住宅所有,"The traditional American Dream is based on **house ownership**.","**House ownership** is a major financial goal for many families.",""
cost of living,phr n,生活費,"The average worker's wages have not kept pace with the **cost of living**.","The **cost of living** is very high in big cities.","high cost of living, low cost of living"
average,adj,平均の、普通の,"The **average** worker's wages have not kept pace with the cost of living.","The **average** temperature this month was higher than usual.","on average, average income, average person"
keep pace with,phr v,～に遅れずについていく,"The average worker's wages have not **kept pace with** the cost of living.","It's hard to **keep pace with** technological advancements.",""
difficulty,n,困難、苦労,"As a result, many people are now finding it **difficulty** to save for retirement.","She faced many **difficulties** during her journey.","face difficulty, overcome difficulty, in difficulty"
prediction,n,予測、予言,"What is your **prediction** for the economy?","His **prediction** about the weather was accurate.","make a prediction, accurate prediction, economic prediction"
forecast,n/v,予測、予報（する）,"Many economists **forecast** continued growth.","The weather **forecast** predicts rain tomorrow.","weather forecast, economic forecast, make a forecast"
stability,n,安定、安定性,"The company is focused on long-term **stability**.","Political **stability** is important for economic development.","economic stability, political stability, financial stability"
critical thinking,phr n,批判的思考,"**Critical thinking** is a key skill for academic readers.","We encourage students to develop their **critical thinking** skills.",""
evaluate,v,評価する,"After you read, you should **evaluate** the information.","We need to **evaluate** the effectiveness of the new program.","evaluate performance, evaluate data, evaluate options"
design,v,デザインする、設計する,"Nowadays, they can **design** and manufacture clothes in as little as four weeks.","She helped me **design** my new website.","design a system, design a product, interior design"
customer,n,顧客、お客さま,"Customers are happy to find something new.","The company provides excellent service to its **customers**.","loyal customer, satisfied customer, customer service"
trend,n,傾向、流行,"Keep up with fast-moving **trends**.","The latest fashion **trends** are very colorful.","market trend, global trend, current trend"
cheaply,adv,安く,"They produce more cotton more **cheaply**.","You can buy fresh produce very **cheaply** at the local market.","buy cheaply, produce cheaply"
thrown away,phr v,捨てられる,"Huge amounts of clothing are **thrown away**.","Don't **throw away** old newspapers; recycle them.",""
copied,v,コピーする、模倣する,"Their designs are often **copied** by other companies.","The student **copied** the answers from a classmate."," illegally copied, exactly copied"
well-off,adj,裕福な、暮らし向きが良い,"Many **well-off** customers buy designer clothes.","They are a very **well-off** family.",""
sure,adj,確信して、きっと,"Not **sure** they are as good as.","I'm **sure** you'll do well on the exam.","be sure, make sure, for sure"
donate,v,寄付する,"I am always **donating** my clothes.","He decided to **donate** a large sum of money to charity.","donate blood, donate to charity"
selfish,adj,利己的な、わがままな,"That is such a **selfish** attitude.","It was **selfish** of him to take all the food.","selfish behavior, selfish act"
study,v,勉強する、研究する,"It's important to **study** fashion in college.","She is **studying** for her final exams.","study abroad, study a subject, study hard"
prefer,v,～を好む,"I **prefer** to buy second-hand clothes.","I **prefer** tea to coffee.","prefer to do, prefer A to B"
planet,n,惑星、地球,"We need to care of the **planet**.","Earth is the only **planet** known to support life.","protect the planet, on the planet"
otherwise,adv,さもなければ、そうでなければ,"**Otherwise**, our children won't have a planet to live on.","You need to hurry; **otherwise**, you'll miss the train.",""
supply,v,供給する,"China and India **supply** a lot of cotton to the world.","The company **supplies** raw materials to factories.","supply demand, supply chain"
costs,n,費用、経費,"It is very important to keep **costs** down.","The project exceeded its estimated **costs**.","production costs, operating costs, cut costs"
developing countries,phr n,発展途上国,"Large multinational companies outsource their production to **developing countries** like Egypt or Cambodia.","Many aid organizations work in **developing countries**.",""
local economies,phr n,地域経済,"Outsourcing benefits **local economies** by providing jobs.","Small businesses are vital to **local economies**.",""
human rights,phr n,人権,"A **human rights** researcher.","We must protect basic **human rights** for everyone.","human rights activist, human rights violation"
basic needs,phr n,基本的なニーズ、必需品,"Garment workers in countries like India and Bangladesh can't afford to pay their **basic needs** like food and healthcare.","Food, water, and shelter are **basic needs**.",""
dust,n,ほこり,"Workers are exposed to chemicals, **dust**, and unsafe levels of noise.","The old house was covered in **dust**.","dust bunny, dust off"
noise,n,騒音,"Unsafe levels of **noise** from sewing machines.","The constant **noise** from the construction site is annoying.","loud noise, background noise, reduce noise"
economist,n,経済学者,"I realize some experts, like the **economist** David Schneider, say that outsourcing benefits local economies.","A well-known **economist** gave a lecture on global trade.","leading economist, chief economist"
providing,v,提供する,"Outsourcing benefits local economies by **providing** jobs.","The school is **providing** free meals to students.","providing services, providing support"
line up,phr v,並ぶ、列を作る,"People in developing countries often **line up** to take jobs in multinational factories.","People started to **line up** an hour before the concert.","line up for, line up against"
improving,v,改善する,"Improving social conditions in the countries where they are located.","The company is always **improving** its products.","improving quality, improving efficiency"
academic,adj,学術的な、学業の,"Distinguishing fact from opinion is a key skill for **academic** readers.","She has a strong **academic** record.","academic year, academic research, academic achievement"
reader,n,読者,"Distinguishing fact from opinion is a key skill for academic **readers**.","The book has attracted many young **readers**.","avid reader, loyal reader, target reader"
true,adj,真実の、本当の,"A **fact** is a **true** statement that can be proven.","Is it **true** that you're moving to another country?","true story, come true, prove true"
statement,n,陳述、声明,"A fact is a true **statement** that can be proven.","The witness made a false **statement** to the police.","make a statement, press statement, opening statement"
proven,v,証明された,"A fact is a true statement that can be **proven**.","The theory has been **proven** correct through experiments.","proven track record, proven method"
express,v,表現する,"An opinion usually **expresses** a person's idea.","It's important to **express** your feelings clearly.","express oneself, express gratitude, express concern"
judgment,n,判断、意見,"An opinion usually expresses a person's idea, **judgment** or position.","I trust her **judgment** on this matter.","pass judgment, sound judgment, good judgment"
position,n,立場、位置,"An opinion usually expresses a person's idea, judgment or **position**.","What is your **position** on this issue?","take a position, leadership position, market position"
support,v,支持する、裏付ける,"What evidence does she use to **support** her claim?","I will **support** you in your decision.","support a claim, support a family, offer support"
claim,n,主張,"What evidence does she use to support her **claim**?","His **claim** to the throne was weak.","make a claim, refute a claim, false claim"
`;

// CSVデータの検証機能
function validateWordsData() {
    try {
        const lines = wordsDataCSV.trim().split('\n');
        console.log(`CSVには ${lines.length - 1} 個の単語が含まれています`);
        
        // 各行のフィールド数をチェック
        const expectedFields = 6;
        let validRows = 0;
        for (let i = 1; i < lines.length; i++) {
            const fields = lines[i].split(',');
            if (fields.length >= expectedFields) {
                validRows++;
            }
        }
        console.log(`有効な単語データ: ${validRows} 個`);
        return validRows > 0;
    } catch (error) {
        console.error('CSVデータの検証中にエラーが発生:', error);
        return false;
    }
}

// アプリ起動時にデータを検証（開発用）
if (typeof window !== 'undefined') {
    document.addEventListener('DOMContentLoaded', validateWordsData);
} else {
    // Node.js環境での使用を想定
    validateWordsData();
}
